name: Testing
run-name: ${{ github.actor }} is testing 🚀
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependancies
        run: npm install
      - name: Run Tests
        run: npm run test:headless
